### PR TITLE
Update Bluefish runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Update Bluefish runtime to 46

### CODE REVIEW

**Comment by ghost** [comment]
@oli747 I've updated Bluefish runtime to version 46 since runtime version 44 has reached end-of-life. Could you test it.

**Comment by oli747** [comment]
> @oli747 I've updated Bluefish runtime to version 46 since runtime version 44 has reached end-of-life. Could you test it.

seems to work nicely, thanks!

**Comment by oli747** [comment]
> @oli747 I've updated Bluefish runtime to version 46 since runtime version 44 has reached end-of-life. Could you test it.

hmm if I have the flatpak version of bluefish run "make" it cannot find gcc for some reason - but that might be an issue with the previous build as well. Could be a flatpak security thing, but how to fix this?

**Comment by ghost** [comment]
Could you ask to discourse? I have very limited knowledge about Flatpak.

https://discourse.flathub.org/

**Pull request merged**
